### ISSUE TITLE
Documentation not in ROS2?

### ISSUE THREAD

**Issue by whitealex95** [ROBOTIS-GIT/emanual#1035]
Hi, I thought that the turtlebot3 works in ROS2 environment and I think the ROS1 manual is a bit outdated.
Is there a documentation for the ROS2 version as well?

**Comment by ROBOTIS-David** [comment]
Hi, whitealex95. 
You can use TurtleBot3 at ROS 2 environment; [e-Manual](http://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_setup/#setup)
Note: TurtleBot3 at ROS 2 is still under development, so that some of contents can not be used at present.

**Comment by ROBOTIS-Will** [comment]
This issue thread is not active so I'll close it. Please feel free to reopen if necessary.
