### ISSUE TITLE
Wrong KpD for xl430-w250 ?

### ISSUE THREAD

**Issue by 3sigma** [ROBOTIS-GIT/emanual#1061]
Hello,

According to the emanual, KpD is equal to KPD = KPD(TBL) / 16. Since KPD(TBL) is equal to 4000, it gives a very big value. It doesn't seem to be realistic.
On the other hand, when you look at the drawing of the position controller, it is written that KpD is entry 82 in the table, not 80.
So I have the impression that KpD and KpI are switched. I think it should be:
KPD = KPD(TBL) / 65,536
and
KPI = KPI(TBL) / 16

Thanks in advance,

Nicolas

**Comment by ROBOTIS-David** [comment]
Hi, this question has not handles for long time. 

If you have any other questions, please contact our support email: support@robotis.com

Thank you,
