### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by sguysc** [ROBOTIS-GIT/emanual#1072]
Please update the website regarding the installation manual of the ROS packages,
that you should download the branch of the distribution you need. For example:
git clone **-b kinetic-devel** https://github.com/ROBOTIS-GIT/open_manipulator.git

Just wasted an hour on this trying to figure out why it keeps crashing  :(

**Comment by ROBOTIS-Will** [comment]
I believe this issue is now resolved after the open_manipulator source code update.
Please feel free to let us know if you're still experiencing problem with our eManual.
Thank you very much for your contribution.
