### ISSUE TITLE
모터 이미지 변경 건

### ISSUE THREAD

**Issue by robotpilot** [ROBOTIS-GIT/emanual#108]
http://emanual.robotis.com/docs/en/dxl/x/xm430-w210/
XM 시리즈의 혼에 대한 설명인데 MX28의 사진이 사용되었습니다.  변경이 요구됩니다.

**Comment by ROBOTIS-Will** [comment]
혼과 써레이션 기어의 얼라인먼트를 맞추는데 초점을 둔 사진이라서 MX제품의 사진을 그대로 사용했습니다.
품질관리팀에 X시리즈의 사진으로 업데이트가 가능한지 문의해보겠습니다.
감사합니다.

**Comment by ROBOTIS-Will** [comment]
X 시리즈의 컨텐츠가 업데이트되었습니다. 감사합니다.
