### ISSUE TITLE
Manual does not display properly when using HTTPS

### ISSUE THREAD

**Issue by russkel** [ROBOTIS-GIT/emanual#1110]
I have an addon called Smart HTTPS which attempts to force all sites to use HTTPS. When browsing the manual none of the style sheets seem to load when using a https URL.

**Comment by ROBOTIS-David** [comment]
@russkel Hi, Thank you for raising the https issue, I am looking for the solution now. Once it is resolved, I will let you know !

**Comment by ROBOTIS-David** [comment]
@russkel 

Hi,russkel 

You can access to the e-Manual with the secure protocol, https. 

I hope I wan not too late for your work. 

If you are okay, I will close this ticket. 

Have a good day :)

**Comment by russkel** [comment]
Works great. Thanks for fixing.
