### ISSUE TITLE
e-Manual Issue

### ISSUE THREAD

**Issue by ROBOTIS-David** [ROBOTIS-GIT/emanual#1121]
http://emanual.robotis.com/docs/kr/edu/engineer/kit2_introduction/#개요
에서 수정 사항 발견했습니다. 영문에서 국문으로 수정 부탁 드립니다. 

![image](https://user-images.githubusercontent.com/48426280/82541243-1bf4aa00-9b8b-11ea-85b9-13f90f148e40.png)

**Comment by ROBOTIS-Will** [comment]
This issue is resolved here #1120
