### ISSUE TITLE
Profile Acceleration and PWM

### ISSUE THREAD

**Issue by swinterbotix** [ROBOTIS-GIT/emanual#1162]
If a motor is set to operate in PWM mode, does the Profile Acceleration register do anything? From the docs, it says that Profile Acceleration applies to all control modes except for current - but I fail to see how it applies to PWM as well...

**Comment by ROBOTIS-David** [comment]
Hi !@swinterbotix  

I am very sorry for missing your ticket and thank you so much for your report. 

Yes you are right, PWM Mode is not compatible with Profile Acceleration as it controls the duty ratio ! 

The contents has been updated, please [check it out](https://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#profile-acceleration108) !

**Comment by swinterbotix** [comment]
Awesome! Looks good. Thanks!
