### ISSUE TITLE
catkin_package() DEPENDS on 'Eigen3' but neither 'Eigen3_INCLUDE_DIRS' nor   'Eigen3_LIBRARIES' is defined.

### ISSUE THREAD

**Issue by MayurRabadiya** [ROBOTIS-GIT/emanual#1176]
catkin_package() DEPENDS on 'Eigen3' but neither 'Eigen3_INCLUDE_DIRS' nor
  'Eigen3_LIBRARIES' is defined.
What is this above error shows?
How can i Solve it?

**Comment by ROBOTIS-David** [comment]
@MayurRabadiya 

Hi, Thank you for your issue ticket :) 

As we provide more than one platform service on ROS, it is hard to check your error code. Could you give me more details about the error? What Platform robot are you using? 

But it seems to me that the error is only issue for ROS Kinetic only. 

You can find some answers regarding the ROS Kinetic Eigen3 from the [ROS ANSWER](https://answers.ros.org/question/253588/ros-kinetic-eigen/). Could you look at the given link, and check it helps? 

Thank you.
