### ISSUE TITLE
Install manual update request

### ISSUE THREAD

**Issue by rjshim** [ROBOTIS-GIT/emanual#1189]
@ROBOTIS-David ( cc: @ROBOTIS-Will )

OM-X: https://emanual.robotis.com/docs/en/platform/openmanipulator_x/ros2_setup/#install-ros-2-on-pc
OM-P: https://emanual.robotis.com/docs/en/platform/openmanipulator_p/ros2_setup/#ros-setup

```sh
# Old
$ wget https://raw.githubusercontent.com/ROBOTIS-GIT/open_manipulator/ros2/install_ros_dashing.sh && chmod 755 ./install_ros_dashing.sh && bash ./install_ros_dashing.sh

# New
$ https://raw.githubusercontent.com/ROBOTIS-GIT/robotis_tools/master/install_ros2_dashing.sh \
&& chmod 755 ./install_ros_dashing.sh \
&& bash ./install_ros_dashing.sh
```

Ryan

**Comment by rjshim** [comment]
@ROBOTIS-Will 

Merge request after done with the manual update. 
(https://github.com/ROBOTIS-GIT/open_manipulator/pull/187)

Thank you

**Comment by ROBOTIS-Will** [comment]
@ROBOTIS-David Watch out for the missing `wget` and simply use a new command instead of new line backslash in the command.

> ```shell
> # New
> $ wget https://raw.githubusercontent.com/ROBOTIS-GIT/robotis_tools/master/install_ros2_dashing.sh
> $ chmod 755 ./install_ros_dashing.sh
> $ bash ./install_ros_dashing.sh
> ```

**Comment by ROBOTIS-Will** [comment]
@ROBOTIS-David Please apply this change to [https://emanual.robotis.com/docs/en/platform/openmanipulator_x/ros2_setup/#install-ros-2-on-pc] section
