### ISSUE TITLE
How to repair XM540 when the gearbox is broken?

### ISSUE THREAD

**Issue by hiter123** [ROBOTIS-GIT/emanual#1206]
when I use the DYNAMIXEX motor type XM540 ，the gearbox is easy to broken when there is some impact or vibration，so I want to ask if there is gear accessories to replace the broken one? thank you very mach

**Comment by ROBOTIS-David** [comment]
@hiter123 

Hi, currently the X540's gears are not ready to be on the sale, but we have a plan to release the gears for X540's soon (Maybe in Oct) 

Thank you,

**Comment by ROBOTIS-David** [comment]
Since this ticket has no additional issue, I would like to close it. 

If any questions may be, please contact the ROBOTIS Support email: support@robotis.com
