### ISSUE TITLE
How to get the transfer function or time constant  in current control model.

### ISSUE THREAD

**Issue by scoard** [ROBOTIS-GIT/emanual#1331]
Hello!
 I'd like to ask you some question. 
1. What is the transfer function of XM430-W350 in current control mode?
2. What is the time constant of XM430-W350 in current control mode?
OR
How to get the transfer function of XM430-W350 in current control mode?
 How to get the time constant of XM430-W350 in current control mode?

**Comment by ROBOTIS-David** [comment]
Hi, @scoard 

Unfortunately, the system function (Gains and Phase) in DYNAMIXEL is not disclosed.  

Why do you need these ?
