### ISSUE TITLE
Noetic SBC setup - wrong password

### ISSUE THREAD

**Issue by saguilera3** [ROBOTIS-GIT/emanual#1374]
On the Noetic SBC setup in the manual, on point "3.2.6 Configure the WiFi Network Setting", on point 1 "Boot Up the Raspberry Pi",  in point "e", you say that the user ID and Password are "ubuntu", but the Password actually is "turtlebot"

**Comment by ROBOTIS-David** [comment]
Thank you for bringing this to my attention , I've already updated the password as "turtlebot" !

**Comment by ROBOTIS-David** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
