### ISSUE TITLE
Trouble on configuring the Raspberry Pi Camera

### ISSUE THREAD

**Issue by fabiocyro** [ROBOTIS-GIT/emanual#1446]
Hello, I want to configure a Pi Camera for my turtlebot3 (burger)

But while following the tutorial and typing sudo raspi-config I got a message of command not found. 

After some research i've managed to install the raspi-config but then I ran into some more trouble: My raspi-config interface doesn't have the Interfacing Options and it keeps saying that is on the latest version after clicking on Update.

So now I'm stuck.

I'm using a Rasberry Pi 3B+ ros melodic ubuntu 18.04

Thanks in advance, any help appreciated

**Comment by ProfJust** [comment]
As far as I know, there is no "raspi-config" when you use Ubuntu, only on other Raspberry PI - OS.
