### ISSUE TITLE
TB3 SCB [Noetic] image file username and password

### ISSUE THREAD

**Issue by IST-DEV20** [ROBOTIS-GIT/emanual#1524]
I download the [Noetic] scb image file from the link https://www.robotis.com/service/download.php?no=2008
and write the image file using the Etcher.
After booting with that, it's not login, it's stop at the text mode and ask for Username and Password.
Please help us, what are the Username and Password of the TB3 SCB [Noetic] version.
Thank you.

**Comment by IST-DEV20** [comment]
Sorry, my fault.
Login with ID ubuntu and PASSWORD turtlebot.

Closed

**Comment by ROBOTIS-Yang** [comment]
Solved
