### ISSUE TITLE
deprecated names

### ISSUE THREAD

**Issue by Nbot07** [ROBOTIS-GIT/emanual#441]
It appears some of the names of files and directories were changed, but the manual is still using some old names e.g. robotis_op3_walking.launch --> op3_walking.launch

Source: 
https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-Common/commit/e713d70c0a4bbfd557683f060c8efd2acc07c5c0

**Comment by ROBOTIS-Will** [comment]
Thank you for reporting the issue 👍 
I'll have our engineer to take a look at the command.
