### ISSUE TITLE
Wrong dynamixel sdk mac instruction

### ISSUE THREAD

**Issue by RaySuhyunLee** [ROBOTIS-GIT/emanual#443]
Hi. I was just looking around and found some errors in the following instruction:

[Dynamixel SDK Mac setup](https://github.com/ROBOTIS-GIT/emanual/blob/master/docs/en/software/dynamixel/dynamixel_sdk/library_setup/cpp_macos.md)

The instruction seems to be the same as one for linux. For instance, `apt get` should be changed to `brew` or some other package managers that OSX supports.

In my case, compiling with my builtin LLVM v.8.1.0 worked just fine.

**Comment by ROBOTIS-Will** [comment]
Hi, @RaySuhyunLee 

Thank you for the report. @kijongGil is currently going over the Dynamixel SDK Mac contents.
Please feel free to report any other contents with wrong information.
Thank you!
