### ISSUE TITLE
Performance graph - Current scale

### ISSUE THREAD

**Issue by ozzdemir** [ROBOTIS-GIT/emanual#460]
![image](https://user-images.githubusercontent.com/30624975/45087545-9014c300-b106-11e8-92b3-6f0fa6a8e0cb.png)
Here on the performance graph of xl-430, current scale seems weird. Some divisions mean 0.2 A, some are 0.1 A. Is it a typo or current-torque relation is not linear as seen in graph?

**Comment by ROBOTIS-Will** [comment]
Thank you for reporting the typo.
Revised graph has been uploaded with #463
