### ISSUE TITLE
SLAM WITH TOF SENSOR(pcd data format)

### ISSUE THREAD

**Issue by archana-l** [ROBOTIS-GIT/emanual#478]
Hi,
I wanted to replace ToF sensor(OPT8241) with lidar sensor in turtlebot 3 burger and implement slam on it. Is it possible? and how can i do that?

**Comment by ROBOTIS-Will** [comment]
@archana-l 
Hi,
For the inquiry regarding TurtleBot3, please use [TurtleBot3 repository](https://github.com/ROBOTIS-GIT/turtlebot3) or [ROS discourse](https://discourse.ros.org/)
Thank you.
