### ISSUE TITLE
some missing in machine learning tutorial

### ISSUE THREAD

**Issue by LeonJung** [ROBOTIS-GIT/emanual#483]
http://emanual.robotis.com/docs/en/platform/turtlebot3/machine_learning/#installation

while following just the tutorial written, and when I launched the stage 2 roslaunch, it suddenly needs cuda ver 9 / cudnn 7, but never described on.

cuda now supports with ver 10 (automatically installed with this), and you know that cuda versions are noncooperative to another.

best.

**Comment by kijongGil** [comment]
Hi @LeonJung :)
Thanks to your contribution.
I will check this issue and update solution.

Thanks,
Gilbert.
