### ISSUE TITLE
[TxRxResult] There is no status packet! and the motor doesn't work

### ISSUE THREAD

**Issue by d0ngha0** [ROBOTIS-GIT/emanual#639]
Hi! There are some issues when I try making XM430-W350-R work. I use U2D2 as the connector and install the lib on python Linux by following the url http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/python_linux/#python-linux. when I run python read_write.py, it doesn't work so I run sudo python read_write.py. It do start working, but the motor doesn't move. The message shows like this:

Succeeded to open the port
Succeeded to change the baudrate
[TxRxResult] There is no status packet!
Press any key to continue! (or press ESC to quit!)
[TxRxResult] There is no status packet!
[TxRxResult] There is no status packet!
[ID:001] GoalPos:010  PresPos:000
Press any key to continue! (or press ESC to quit!)
[TxRxResult] There is no status packet!
[TxRxResult] There is no status packet!
[ID:001] GoalPos:4000  PresPos:000
[TxRxResult] There is no status packet!
[ID:001] GoalPos:4000  PresPos:000
[TxRxResult] There is no status packet!
[ID:001] GoalPos:4000  PresPos:000
[TxRxResult] There is no status packet!
[ID:001] GoalPos:4000  PresPos:000

What should I do to fix this? Did I do anything wrong?

**Comment by ROBOTIS-Will** [comment]
Hi, please use DynamixelSDK issue page for this.
[https://github.com/ROBOTIS-GIT/DynamixelSDK/issues](https://github.com/ROBOTIS-GIT/DynamixelSDK/issues)
Thank you.
