### ISSUE TITLE
Ask about a software for real-time plot of velocity

### ISSUE THREAD

**Issue by HoEmpire** [ROBOTIS-GIT/emanual#640]
https://www.youtube.com/watch?v=6Pnz26p_FjY
This video show the function of time-based profile and in the video, a software was used to plot the curve of the veloctiy?
Could you tell me what kind of software was used in this video to plot the velocity data？﻿
Besides, in the e-manual, I didn't find the response time of the servo, do you have any data about the response time of **MX64** and **MX106**.
Thank you!

**Comment by ROBOTIS-Will** [comment]
Hi, this is issue page is intended for reporting errors in eManual.
Please use forum in Robotis homepage.
[http://en.robotis.com/service/forum.php](http://en.robotis.com/service/forum.php)
Thank you.
