### ISSUE TITLE
Navigation Goal is not runing

### ISSUE THREAD

**Issue by cdacrobo1** [ROBOTIS-GIT/emanual#806]
Hey, we are using Turtlebot3 Burger and have faced several problem. We have successfully done upto 10.1 Run Navigation Nodes using your manual ROBOTICS e-Manual(http://emanual.robotis.com/docs/en/platform/turtlebot3/navigation/#run-navigation-nodes). But when we are trying to sending the end position for navigation then it is not working. We are sucked on 10.3 Estimate Initial Pose for past 1 months. We already tried to connect several time from Roborium who are the selling team of Turtlebot in India. But there have no fruit full work is done. So now we want a full support from your side to send the navigation goal.

**Comment by ROBOTIS-Will** [comment]
@cdacrobo1 Hi, please use TurtleBot3 issue page for this. Thank you.
[https://github.com/ROBOTIS-GIT/turtlebot3/issues](https://github.com/ROBOTIS-GIT/turtlebot3/issues)
