### ISSUE TITLE
BT410 garbage value

### ISSUE THREAD

**Issue by HwangHanGyeol** [ROBOTIS-GIT/emanual#850]
OpenCR and BT410 modules are used.
When the BT410 module is disconnected, the garbage value comes on.
How can we solve this?

**Comment by ROBOTIS-Will** [comment]
@HwangHanGyeol,
Hi, please use OpenCR Issue thread below.
Thank you.
[https://github.com/ROBOTIS-GIT/OpenCR/issues](https://github.com/ROBOTIS-GIT/OpenCR/issues)
